// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt1HnD-Y2RLpFZLZ-F5loFiYYVHnmzGnw',
    appId: '1:265955884256:web:bfd448c665ab4878e96485',
    messagingSenderId: '265955884256',
    projectId: 'mascota-virtual-7a0ae',
    authDomain: 'mascota-virtual-7a0ae.firebaseapp.com',
    databaseURL: 'https://mascota-virtual-7a0ae-default-rtdb.firebaseio.com',
    storageBucket: 'mascota-virtual-7a0ae.firebasestorage.app',
    measurementId: 'G-4BYER83566',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3gHpdgY7htr0kl6_t3wGMcxsVGSfqi6w',
    appId: '1:265955884256:android:ca90dfbb14ab776ee96485',
    messagingSenderId: '265955884256',
    projectId: 'mascota-virtual-7a0ae',
    databaseURL: 'https://mascota-virtual-7a0ae-default-rtdb.firebaseio.com',
    storageBucket: 'mascota-virtual-7a0ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-knD8S5UJRlhzbZoVsQKlzmI7HBI7qqU',
    appId: '1:265955884256:ios:c7d9a036eaee7ff5e96485',
    messagingSenderId: '265955884256',
    projectId: 'mascota-virtual-7a0ae',
    databaseURL: 'https://mascota-virtual-7a0ae-default-rtdb.firebaseio.com',
    storageBucket: 'mascota-virtual-7a0ae.firebasestorage.app',
    iosBundleId: 'com.example.mascota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-knD8S5UJRlhzbZoVsQKlzmI7HBI7qqU',
    appId: '1:265955884256:ios:c7d9a036eaee7ff5e96485',
    messagingSenderId: '265955884256',
    projectId: 'mascota-virtual-7a0ae',
    databaseURL: 'https://mascota-virtual-7a0ae-default-rtdb.firebaseio.com',
    storageBucket: 'mascota-virtual-7a0ae.firebasestorage.app',
    iosBundleId: 'com.example.mascota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt1HnD-Y2RLpFZLZ-F5loFiYYVHnmzGnw',
    appId: '1:265955884256:web:4b8a1c5bd51bebe3e96485',
    messagingSenderId: '265955884256',
    projectId: 'mascota-virtual-7a0ae',
    authDomain: 'mascota-virtual-7a0ae.firebaseapp.com',
    databaseURL: 'https://mascota-virtual-7a0ae-default-rtdb.firebaseio.com',
    storageBucket: 'mascota-virtual-7a0ae.firebasestorage.app',
    measurementId: 'G-DQR8F9PCBZ',
  );
}
